server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hb_sms_server
    username: root
    password: interOP@123
    tomcat.max-wait: 20000
    tomcat.max-active: 50
    tomcat.max-idle: 20
    tomcat.min-idle: 15
    validationQuery: SELECT 1
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      show_sql: true

  redis:
    port: 6379
    password: password
    host: localhost

management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
